// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zgIf1MpugvqfmvjYreqZCTcUmz1rjIM',
    appId: '1:555894672261:web:4d87db6b5641c2ec5ed2ec',
    messagingSenderId: '555894672261',
    projectId: 'delivery-food-6a446',
    authDomain: 'delivery-food-6a446.firebaseapp.com',
    storageBucket: 'delivery-food-6a446.appspot.com',
    measurementId: 'G-9M1M094PW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkqBLJd2FfaU0ghYKaziEl__ItGutu2w',
    appId: '1:555894672261:android:b53e7012722f0a2c5ed2ec',
    messagingSenderId: '555894672261',
    projectId: 'delivery-food-6a446',
    storageBucket: 'delivery-food-6a446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCk6U2F0_rqATfK7277kEvNSChPTVc2VM',
    appId: '1:555894672261:ios:54f41028215302875ed2ec',
    messagingSenderId: '555894672261',
    projectId: 'delivery-food-6a446',
    storageBucket: 'delivery-food-6a446.appspot.com',
    iosClientId: '555894672261-f1gm5btigefjh5tc3ppnsugr1ode5p3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCk6U2F0_rqATfK7277kEvNSChPTVc2VM',
    appId: '1:555894672261:ios:54f41028215302875ed2ec',
    messagingSenderId: '555894672261',
    projectId: 'delivery-food-6a446',
    storageBucket: 'delivery-food-6a446.appspot.com',
    iosClientId: '555894672261-f1gm5btigefjh5tc3ppnsugr1ode5p3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5zgIf1MpugvqfmvjYreqZCTcUmz1rjIM',
    appId: '1:555894672261:web:45d287580d7d49c85ed2ec',
    messagingSenderId: '555894672261',
    projectId: 'delivery-food-6a446',
    authDomain: 'delivery-food-6a446.firebaseapp.com',
    storageBucket: 'delivery-food-6a446.appspot.com',
    measurementId: 'G-HVPYL1NZW7',
  );
}
